In [11]:
import numpy as np
v=np.array([2,5,4,9,3,8])
v

array([2, 5, 4, 9, 3, 8])

In [12]:
np.var(v)

np.float64(6.472222222222222)

In [13]:
np.std(v)

np.float64(2.544056253745625)

In [14]:
m=np.mean(v)
m

np.float64(5.166666666666667)

In [15]:
y=m-v
y

array([ 3.16666667,  0.16666667,  1.16666667, -3.83333333,  2.16666667,
       -2.83333333])

In [16]:
b=y**2
b

array([10.02777778,  0.02777778,  1.36111111, 14.69444444,  4.69444444,
        8.02777778])

In [17]:
u=np.sum(b)/len(v)
u

np.float64(6.472222222222222)

In [18]:
c=np.sqrt(u)
c

np.float64(2.544056253745625)

In [26]:
x=np.array([5,10,5,11,12,4,3,2,7,1])
y=np.array([1,6,2,8,5,1,4,6,5,2])
print(sum(x))  # sum of x
print(sum(y))  # sum of y
print("square of x",x**2)  # sqr of x   
print("sqr of y ",y**2)    # sqr of y
print(y**4)

60
40
square of x [ 25 100  25 121 144  16   9   4  49   1]
sqr of y  [ 1 36  4 64 25  1 16 36 25  4]
[   1 1296   16 4096  625    1  256 1296  625   16]

In [30]:
import pandas as pd

In [7]:
import pandas as pd

x = [2,4,6,8,10]
y = [12,11,8,3,1]

df = pd.DataFrame({
    "X": x,
    "Y": y
})

print(df)

    X   Y
0   2  12
1   4  11
2   6   8
3   8   3
4  10   1

In [8]:
df.corr()

          X         Y
X  1.000000 -0.978492
Y -0.978492  1.000000

In [9]:
df.cov()

      X     Y
X  10.0 -15.0
Y -15.0  23.5

In [10]:
df.var()

X    10.0
Y    23.5
dtype: float64

In [ ]:
##   Inferential statistics
1. hypothesis testing
  a. t test  > n number of test less than 30 prefer t test ( n<30 ), std is not given.
             > A t test is inferential statistics used to determine, if there is a significant  diffeneces  between the mean of two groups,which may be released or independent. It is primerely used when sample size are smaller than 30 (<30) or when the population std is unknown helping to decide whether to reject the null hypothesis.
  b. z test > n number of test is greater than 30 prefe z test ( n>30) , st